### ISSUE TITLE
Wrong sprite generation

### ISSUE THREAD

**Issue by mahnunchik** [noveogroup/gulp-spritegen#1]
Wrong sprite generation after `canvas` update.
### canvas@1.1.6

![icons 2x](https://cloud.githubusercontent.com/assets/780935/6346651/a97ee59e-bc33-11e4-8d00-948d73045ae7.png)
### canvas@1.2.1

![icons 2x](https://cloud.githubusercontent.com/assets/780935/6346677/d3776740-bc33-11e4-9f44-731e5f2e2366.png)

**Comment by owanturist** [comment]
:+1:

**Comment by TechnoBerry** [comment]
This bug is already known bug in 'node-canvas' https://github.com/Automattic/node-canvas/issues/512
I fixed node-canvas version to 1.1.6.
